spring:
  config:
    # 导入项目根目录的 .env
    import:
      - optional:file:./.env[.properties]
  application:
    name: ey-ai-code-screenshot
  session:
    store-type: redis
    # session 30 天过期
    timeout: 2592000
server:
  port: 8127
  servlet:
    context-path: /api
# Tencent COS 对象存储服务
cos:
  client:
    host: ${COS_HOST}
    secretId: ${COS_SECRET_ID}
    secretKey: ${COS_SECRET_KEY}
    region: ${COS_REGION}
    bucket: ${COS_BUCKET_NAME}
# Dubbo
dubbo:
  registry:
    address: nacos://127.0.0.1:8848
    register-mode: instance
  protocol:
    name: tri
    port: 50052
  consumer:
    timeout: 120000
  provider:
    timeout: 120000
